### PR TITLE
Feature - Add subcommand for uploading from aws s3 to greenfiled

### PR DESCRIPTION
**Pull request by jeongseup**
### Support S3  commands and CancelAllObjects once
   cancel-all-create-obj  cancel all the created object
   s3-ls-bucket           list s3 buckets in specific region
   s3-ls                  list objects of the aws s3 bucket in specific region
   s3-download-objects    download all objects in the aws s3 bucket
   s3-migration-objects   migration all object in the aws specific bucket

### Rationale

Easy migrationing from aws s3 to greenfiled for developers

### Cancel Operations

(1) Cancel All Objects

cancel all the created object
```
gnfd-cmd storage cancel-all-create-obj gnfd://testbucket
```

#### S3 Operations

(1) Query AWS S3 bucket list

list s3 buckets in specific region

```
gnfd-cmd storage s3-ls-bucket ap-northeast-2
```

(2) Query AWS S3 Objects in specific bucket

list objects of the aws s3 bucket in specific region
```
gnfd-cmd storage s3-ls ap-northeast-2 before-bucket
```

(3) Download AWS S3 Objects in specific bucket

download all objects in the aws s3 bucket
```
gnfd-cmd storage s3-download-objects ap-northeast-2 before-bucket ./downloads
```

(4) Migration All Objects from AWS S3 to Greenfiled

Migration all objects from in the aws s3 bucket
```
gnfd-cmd storage s3-migration-objects ap-northeast-2 before-bucket after-bucket
```

### Changes

Notable changes:
* add each change in a bullet point here
* ...

### CODE REVIEW

**Comment by zjubfd** [comment]
Thanks for contributing, the team is evaluating this PR

**Comment by flywukong** [comment]
@Jeongseup  Adding the capability to migrate or list S3 data within gnfd-cmd is a great feature.
Could you rebase the latest changes from the master branch and submit the pull request to the master branch? And it is  suggested adding a separate S3 subcommand, distinct from the storage subcommands, such as `gnfd-cmd s3 s3-migrate-objects.`
Additionally, we currently use Keystore to manage keys. Your AWS S3 access key and secret key can be stored in the keystore directory under a new name.

**Comment by Jeongseup** [comment]
Basically, I made this PR through [Glitch Hackerton BNB track](https://youtu.be/_U-ubzDDP4M?si=RtU88vepIyXTtYKH). I remembered [the track](https://x.com/GlitchHackathon/status/1637723690547937281?s=20) was creating S3 migration tools for BNB greenfiled chain. 

So, I created two PR for BNB tracks. First one is this PR and the other one is https://github.com/bnb-chain/greenfield-go-sdk/pull/74

By your reponses, I agree with you that this PR should need to re-create with rebase to master branch. And I want to ask you guys this PR is still valid now? If you say it's valid and ask for update this PR, I would do.

Thank you for your response 👍

**Comment by flywukong** [comment]
@Jeongseup  Yes,  it is valid. Please follow our suggestions to update PR by adding a separate S3 subcommand to finish the s3 related fucntions .  Thank you. Please also pay attention to the code style and use English comments.

**Comment by Jeongseup** [comment]
> @Jeongseup Yes, it is valid. Please follow our suggestions to update PR by adding a separate S3 subcommand to finish the s3 related fucntions . Thank you. Please also pay attention to the code style and use English comments.
Do you have a code style guide for PR? Please share a link or something for me

**Pull request closed without merging**
